spring.application.name=pix-recorrente-seguro
app.storage.agendamentos-file=data/agendamentos.json
springdoc.swagger-ui.path=/swagger-ui.html

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=pix-recorrente-antifraude
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.midway.pix.infrastructure.kafka.event
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties[max.block.ms]=3000
spring.kafka.admin.fail-fast=false
spring.kafka.admin.properties[default.api.timeout.ms]=3000
spring.kafka.admin.properties[request.timeout.ms]=3000
spring.kafka.listener.missing-topics-fatal=false
logging.level.org.apache.kafka=WARN
logging.level.org.apache.kafka.clients.NetworkClient=ERROR

app.kafka.topic.agendamento-solicitado=agendamento-solicitado
